"""Trigger engine + routes (DL-120).

Covered: store CRUD + persistence roundtrip against a tmp DATA_DIR, the
minute-edge for time triggers, on-entry-only semantics for app/agent
triggers (with a baseline first observation), webhook dispatch, action
dispatch through a fake executor, ``trigger_fired`` payloads, and the
route's auth/localhost split.
"""
import json
import os
import sys
import threading
from datetime import datetime

import pytest
from flask import Flask

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from config import Config  # noqa: E402
from auth import AuthManager  # noqa: E402
from actions.base_action import ActionResult  # noqa: E402
from integrations import agent_state  # noqa: E402
from services import triggers  # noqa: E402
from routes import triggers as trigger_routes  # noqa: E402
from utils import app_monitor  # noqa: E402

MONDAY = datetime(2025, 1, 6, 7, 30, 5)    # weekday() == 0
TUESDAY = datetime(2025, 1, 7, 7, 30, 5)   # weekday() == 1


@pytest.fixture
def store(tmp_path, monkeypatch):
    """Empty trigger store in a tmp DATA_DIR; engine state fully reset."""
    monkeypatch.setattr(Config, 'DATA_DIR', tmp_path)
    triggers.reset()
    yield tmp_path
    triggers.reset()


@pytest.fixture
def emitted(monkeypatch):
    events = []
    monkeypatch.setattr(
        triggers, '_emit', lambda name, payload: events.append((name, payload))
    )
    return events


@pytest.fixture
def client(store):
    """Standalone app with just the triggers blueprint — app.py wiring is
    the orchestrator's, so routes are tested on a bare app."""
    flask_app = Flask(__name__)
    flask_app.config['TESTING'] = True
    flask_app.register_blueprint(trigger_routes.triggers_bp)
    with flask_app.test_client() as test_client:
        yield test_client


def _fired(events):
    return [p for n, p in events if n == 'trigger_fired']


def _notify_trigger(**over):
    body = {
        'event': {'type': 'time', 'at': '07:30'},
        'action': {'type': 'show_notification', 'title': 'Hi', 'message': 'm'},
    }
    body.update(over)
    return body


# ---------------------------------------------------------------------------
# Store / validation
# ---------------------------------------------------------------------------

def test_add_list_get_roundtrip(store):
    trigger = triggers.add_trigger(_notify_trigger())
    assert trigger['id'].startswith('trg_')
    assert trigger['enabled'] is True
    assert triggers.get_trigger(trigger['id'])['label'] == trigger['label']
    assert [t['id'] for t in triggers.list_triggers()] == [trigger['id']]


def test_store_survives_reload(store):
    trigger = triggers.add_trigger(_notify_trigger())
    triggers.reset()  # drop the in-memory copy — next read hits the file
    assert [t['id'] for t in triggers.list_triggers()] == [trigger['id']]


def test_corrupt_store_is_empty_not_fatal(store):
    (store / 'triggers.json').write_text('{broken', encoding='utf-8')
    assert triggers.list_triggers() == []


@pytest.mark.parametrize('patch', [
    {'event': {'type': 'time', 'at': '25:00'}},
    {'event': {'type': 'time', 'at': '07:30', 'days': ['mon']}},
    {'event': {'type': 'app_foreground'}},
    {'event': {'type': 'agent_state', 'source': 'hal', 'state': 'ready'}},
    {'event': {'type': 'agent_state', 'source': 'claude', 'state': 'sleeping'}},
    {'event': {'type': 'nope'}},
    {'action': {'type': 'execute_action', 'action': {'config': {}}}},
    {'action': {'type': 'switch_scene'}},
    {'action': {'type': 'show_notification'}},
    {'action': {'type': 'nope'}},
])
def test_invalid_specs_raise_value_error(store, patch):
    body = _notify_trigger(**patch)
    with pytest.raises(ValueError):
        triggers.add_trigger(body)


def test_webhook_key_autogenerated_and_validated(store):
    trigger = triggers.add_trigger({
        'event': {'type': 'webhook'},
        'action': {'type': 'show_notification', 'title': 'x'},
    })
    assert trigger['event']['key'].startswith('whk_')
    with pytest.raises(ValueError):
        triggers.add_trigger({
            'event': {'type': 'webhook', 'key': 'bad key!'},
            'action': {'type': 'show_notification', 'title': 'x'},
        })


def test_update_merges_and_replaces(store):
    trigger = triggers.add_trigger(_notify_trigger())
    updated = triggers.update_trigger(trigger['id'], {
        'label': 'Renamed', 'enabled': False,
        'event': {'type': 'app_foreground', 'exe': 'spotify.exe'},
    })
    assert updated['label'] == 'Renamed'
    assert updated['enabled'] is False
    assert updated['event']['exe'] == 'spotify.exe'
    assert updated['action'] == trigger['action']
    assert triggers.update_trigger('trg_missing', {'label': 'x'}) is None


def test_remove(store):
    trigger = triggers.add_trigger(_notify_trigger())
    assert triggers.remove_trigger(trigger['id']) is True
    assert triggers.remove_trigger(trigger['id']) is False
    assert triggers.list_triggers() == []


# ---------------------------------------------------------------------------
# Event matching
# ---------------------------------------------------------------------------

def test_time_trigger_fires_once_per_matching_minute(store, emitted):
    triggers.add_trigger(_notify_trigger())
    triggers._tick(MONDAY)
    triggers._tick(MONDAY.replace(second=45))
    assert len(_fired(emitted)) == 1
    # A different minute with a non-matching at fires nothing.
    triggers._tick(MONDAY.replace(minute=31))
    assert len(_fired(emitted)) == 1
    # Same minute the next day is a fresh edge.
    triggers._tick(TUESDAY)
    assert len(_fired(emitted)) == 2


def test_time_trigger_days_filter(store, emitted):
    triggers.add_trigger(_notify_trigger(
        event={'type': 'time', 'at': '07:30', 'days': [1]},  # Tuesdays only
    ))
    triggers._tick(MONDAY)
    assert _fired(emitted) == []
    triggers._tick(TUESDAY)
    assert len(_fired(emitted)) == 1


def test_disabled_trigger_never_fires(store, emitted):
    triggers.add_trigger(_notify_trigger(enabled=False))
    triggers._tick(MONDAY)
    assert _fired(emitted) == []


def test_app_trigger_fires_on_entry_only(store, emitted, monkeypatch):
    current = ['chrome.exe']
    monkeypatch.setattr(
        app_monitor, 'get_current_active_app',
        lambda: {'exe': current[0], 'name': current[0]},
    )
    triggers.add_trigger({
        'event': {'type': 'app_foreground', 'exe': 'Spotify.exe'},
        'action': {'type': 'switch_scene', 'scene': 'Media'},
    })
    triggers._tick()                       # baseline observation: chrome
    current[0] = 'spotify.exe'
    triggers._tick()                       # entry → fire (case-insensitive)
    triggers._tick()                       # sustained → no refire
    current[0] = 'chrome.exe'
    triggers._tick()                       # leaving re-arms
    current[0] = 'spotify.exe'
    triggers._tick()                       # second entry → fire
    assert len(_fired(emitted)) == 2
    navs = [p for n, p in emitted if n == 'navigate_scene']
    assert navs == [{'scene': 'Media'}, {'scene': 'Media'}]


def test_app_trigger_first_observation_is_baseline(store, emitted, monkeypatch):
    """Already-foreground when the engine first looks = no fire — otherwise
    every backend restart while the app is focused re-runs the action."""
    monkeypatch.setattr(
        app_monitor, 'get_current_active_app',
        lambda: {'exe': 'spotify.exe'},
    )
    triggers.add_trigger({
        'event': {'type': 'app_foreground', 'exe': 'spotify.exe'},
        'action': {'type': 'switch_scene', 'scene': 'Media'},
    })
    triggers._tick()
    triggers._tick()
    assert _fired(emitted) == []


def test_agent_trigger_fires_on_entry_only(store, emitted, monkeypatch):
    snapshot = [{'claude': {'state': 'working'}}]
    monkeypatch.setattr(agent_state, 'snapshot', lambda: snapshot[0])
    triggers.add_trigger({
        'event': {'type': 'agent_state', 'source': 'claude', 'state': 'permission'},
        'action': {'type': 'show_notification', 'title': 'Needs you'},
    })
    triggers._tick()                                   # baseline: working
    snapshot[0] = {'claude': {'state': 'permission'}}
    triggers._tick()                                   # entry → fire
    triggers._tick()                                   # sustained → quiet
    snapshot[0] = {'claude': {'state': 'ready'}}
    triggers._tick()                                   # re-arm
    snapshot[0] = {'claude': {'state': 'permission'}}
    triggers._tick()                                   # entry again → fire
    assert len(_fired(emitted)) == 2
    notes = [p for n, p in emitted if n == 'panel_notification']
    assert all(p['source'] == 'trigger' and p['title'] == 'Needs you'
               for p in notes)


def test_agent_trigger_absent_source_rearms(store, emitted, monkeypatch):
    """A source dropping out of the snapshot (TTL/end) counts as leaving."""
    snapshot = [{'claude': {'state': 'working'}}]
    monkeypatch.setattr(agent_state, 'snapshot', lambda: snapshot[0])
    triggers.add_trigger({
        'event': {'type': 'agent_state', 'source': 'claude', 'state': 'permission'},
        'action': {'type': 'show_notification', 'title': 'x'},
    })
    triggers._tick()
    snapshot[0] = {'claude': {'state': 'permission'}}
    triggers._tick()
    snapshot[0] = {}                                    # source gone
    triggers._tick()
    snapshot[0] = {'claude': {'state': 'permission'}}
    triggers._tick()
    assert len(_fired(emitted)) == 2


# ---------------------------------------------------------------------------
# Dispatch + firing
# ---------------------------------------------------------------------------

def test_execute_action_runs_through_executor(store, emitted, monkeypatch):
    calls = []

    class FakeExecutor:
        def execute_action(self, action):
            calls.append(action)
            return ActionResult(True, 'did it')

    monkeypatch.setattr(triggers, '_executor', FakeExecutor())
    triggers.add_trigger({
        'event': {'type': 'webhook', 'key': 'launch'},
        'action': {'type': 'execute_action',
                   'action': {'type': 'url', 'config': {'url': 'http://x'}}},
    })
    assert triggers.fire_webhook_key('launch') == 1
    assert calls == [{'type': 'url', 'config': {'url': 'http://x'}}]
    fired = _fired(emitted)
    assert fired[0]['ok'] is True and fired[0]['detail'] == 'did it'


def test_throwing_executor_degrades_to_ok_false(store, emitted, monkeypatch):
    class Boom:
        def execute_action(self, action):
            raise RuntimeError('nope')

    monkeypatch.setattr(triggers, '_executor', Boom())
    trigger = triggers.add_trigger({
        'event': {'type': 'webhook', 'key': 'boom'},
        'action': {'type': 'execute_action', 'action': {'type': 'url'}},
    })
    triggers.fire_webhook_key('boom')
    fired = _fired(emitted)
    assert len(fired) == 1
    assert fired[0]['ok'] is False and 'nope' in fired[0]['detail']
    assert fired[0]['id'] == trigger['id']
    # And the loop is unharmed — a manual tick still works.
    triggers._tick(MONDAY)


def test_trigger_fired_payload_shape(store, emitted):
    trigger = triggers.add_trigger(_notify_trigger(label='Evening scene'))
    triggers._tick(MONDAY)
    (payload,) = _fired(emitted)
    assert payload['id'] == trigger['id']
    assert payload['label'] == 'Evening scene'
    assert payload['ok'] is True
    assert isinstance(payload['ts'], float)


def test_webhook_key_fires_only_enabled_matching(store, emitted):
    triggers.add_trigger({
        'event': {'type': 'webhook', 'key': 'shared'},
        'action': {'type': 'show_notification', 'title': 'a'},
    })
    triggers.add_trigger({
        'event': {'type': 'webhook', 'key': 'shared'},
        'action': {'type': 'show_notification', 'title': 'b'},
    })
    triggers.add_trigger({
        'event': {'type': 'webhook', 'key': 'shared'},
        'action': {'type': 'show_notification', 'title': 'off'},
        'enabled': False,
    })
    assert triggers.fire_webhook_key('shared') == 2
    assert triggers.fire_webhook_key('nobody') == 0


def test_fire_trigger_test_seam_ignores_enabled(store, emitted):
    trigger = triggers.add_trigger(_notify_trigger(enabled=False))
    ok, detail = triggers.fire_trigger(trigger['id'])
    assert ok is True and detail == 'panel_notification sent'
    assert triggers.fire_trigger('trg_missing') is None


def test_start_spawns_once_and_stop_releases(monkeypatch):
    spawned = []
    monkeypatch.setattr(triggers, '_spawn', lambda fn, *a: spawned.append(fn))
    triggers.reset()
    assert triggers.start() is True
    assert triggers.start() is False
    triggers.stop()
    assert triggers.start() is True
    triggers.stop()
    assert len(spawned) == 2


def test_loop_survives_tick_errors(monkeypatch):
    calls = []
    stop_event = threading.Event()

    def boom():
        calls.append(1)
        if len(calls) >= 2:
            stop_event.set()
        raise RuntimeError('tick exploded')

    monkeypatch.setattr(triggers, '_tick', boom)
    triggers._loop(stop_event, 0)
    assert len(calls) == 2


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

def test_crud_over_http(client):
    assert client.get('/api/triggers').get_json()['triggers'] == []

    created = client.post('/api/triggers', json=_notify_trigger()).get_json()
    assert created['success'] and created['trigger']['id'].startswith('trg_')
    tid = created['trigger']['id']

    updated = client.put(f'/api/triggers/{tid}',
                         json={'label': 'New label'}).get_json()
    assert updated['trigger']['label'] == 'New label'

    assert client.delete(f'/api/triggers/{tid}').get_json()['success']
    assert client.delete(f'/api/triggers/{tid}').status_code == 404


def test_route_validation_errors_are_400(client):
    resp = client.post('/api/triggers', json={'event': {'type': 'nope'},
                                            'action': {'type': 'nope'}})
    assert resp.status_code == 400
    assert not resp.get_json()['success']
    resp = client.put('/api/triggers/trg_x', json={'event': {'type': 'nope'}})
    assert resp.status_code == 400


def test_unknown_trigger_ids_404(client):
    assert client.put('/api/triggers/trg_x', json={'label': 'x'}).status_code == 404
    assert client.delete('/api/triggers/trg_x').status_code == 404
    assert client.post('/api/triggers/trg_x/test').status_code == 404


def test_test_endpoint_fires_and_reports(client, emitted):
    tid = client.post('/api/triggers', json=_notify_trigger()) \
        .get_json()['trigger']['id']
    resp = client.post(f'/api/triggers/{tid}/test')
    body = resp.get_json()
    assert resp.status_code == 200
    assert body['success'] and body['ok'] is True
    assert _fired(emitted)[0]['id'] == tid


def test_webhook_route_fires_and_counts(client, emitted):
    client.post('/api/triggers', json={
        'event': {'type': 'webhook', 'key': 'hooky'},
        'action': {'type': 'show_notification', 'title': 'ping'},
    })
    resp = client.post('/api/triggers/fire/hooky')
    assert resp.get_json() == {'success': True, 'fired': 1}
    assert client.post('/api/triggers/fire/other').get_json()['fired'] == 0


def test_webhook_route_is_localhost_only(client):
    resp = client.post('/api/triggers/fire/hooky',
                       environ_overrides={'REMOTE_ADDR': '192.168.1.50'})
    assert resp.status_code == 403


def test_crud_requires_auth_when_enabled(client, monkeypatch):
    monkeypatch.setattr(Config, 'REQUIRE_AUTH', True)
    assert client.get('/api/triggers').status_code == 401
    assert client.post('/api/triggers', json=_notify_trigger()).status_code == 401
    token = AuthManager.generate_token({'authenticated': True})
    headers = {'Authorization': f'Bearer {token}'}
    assert client.get('/api/triggers', headers=headers).status_code == 200


def test_webhook_skips_auth_even_when_required(client, monkeypatch):
    """Hook scripts can't hold UI tokens — localhost is the whole check."""
    monkeypatch.setattr(Config, 'REQUIRE_AUTH', True)
    resp = client.post('/api/triggers/fire/none')
    assert resp.status_code == 200
    assert resp.get_json()['fired'] == 0


def test_created_trigger_persists_to_disk(client, store):
    client.post('/api/triggers', json=_notify_trigger(label='persisted'))
    on_disk = json.loads((store / 'triggers.json').read_text(encoding='utf-8'))
    assert on_disk['triggers'][0]['label'] == 'persisted'
    assert not (store / 'triggers.json.tmp').exists()


# ---------------------------------------------------------------------------
# Master switch — Settings "pause all triggers"
# ---------------------------------------------------------------------------

def test_master_switch_pauses_engine_and_webhooks(store, emitted):
    tid = triggers.add_trigger(_notify_trigger())['id']
    triggers.add_trigger({
        'event': {'type': 'webhook', 'key': 'k'},
        'action': {'type': 'show_notification', 'title': 'w', 'message': 'm'},
    })
    assert triggers.is_enabled() is True

    triggers.set_enabled(False)
    triggers._tick(MONDAY)
    assert triggers.fire_webhook_key('k') == 0
    assert _fired(emitted) == []

    # Manual test-fire still works — the panel's smoke test stays honest.
    ok, _detail = triggers.fire_trigger(tid)
    assert ok is True
    assert len(_fired(emitted)) == 1


def test_master_switch_persists_with_the_store(store):
    triggers.set_enabled(False)
    on_disk = json.loads((store / 'triggers.json').read_text(encoding='utf-8'))
    assert on_disk['enabled'] is False
    triggers.reset()  # drop memory — reload must pick the flag back up
    assert triggers.is_enabled() is False


def test_resume_rebaselines_edges(store, emitted, monkeypatch):
    """A condition that came true while paused must not fire on resume."""
    snapshot = [{}]
    monkeypatch.setattr(agent_state, 'snapshot', lambda: snapshot[0])
    triggers.add_trigger({
        'event': {'type': 'agent_state', 'source': 'claude',
                  'state': 'permission'},
        'action': {'type': 'show_notification', 'title': 'a', 'message': 'm'},
    })
    triggers._tick()                       # baseline: no state yet
    triggers.set_enabled(False)
    snapshot[0] = {'claude': {'state': 'permission'}}
    triggers._tick()                       # paused — nothing
    triggers.set_enabled(True)             # re-baseline on resume
    triggers._tick()                       # first obs after resume = baseline
    assert _fired(emitted) == []


def test_master_switch_route_roundtrip(client):
    assert client.get('/api/triggers').get_json()['enabled'] is True
    resp = client.put('/api/triggers/enabled', json={'enabled': False})
    assert resp.get_json() == {'success': True, 'enabled': False}
    assert client.get('/api/triggers').get_json()['enabled'] is False
    client.put('/api/triggers/enabled', json={'enabled': True})
    assert triggers.is_enabled() is True
