blank_issues_enabled: false
contact_links:
  - name: VDock Community Discussions
    url: https://github.com/your-org/VDock/discussions
    about: Ask questions and discuss ideas with the community
  - name: VDock Documentation
    url: https://github.com/your-org/VDock/tree/main/docs
    about: Check our comprehensive documentation for answers
  - name: Security Issues
    url: https://github.com/your-org/VDock/security/advisories/new
    about: Report security vulnerabilities privately
